version: '3.8'

networks:
  my_network:

services:
  # Сервис для веб-сервера и PHP
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - my_network

  # Сервис для базы данных MySQL 8
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my_network
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8090:8080"
  #   networks:
  #     - my_network
  #   # Сервис для phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8181:80"
    # environment:
    #   PMA_HOST: db
    #   PMA_PORT: 3306
    networks:
      - my_network